- .github/pull_request_template.md
- config/dev.exs
- config/prod.exs
- config/test.exs
- lib/idea_portal/accounts.ex
- lib/idea_portal/accounts/user.ex
- lib/idea_portal/emails.ex
- lib/idea_portal/mailer.ex
- lib/web/controllers/registration_verify_controller.ex
- lib/web/router.ex
- lib/web/templates/email/verify-email.html.eex
- lib/web/views/email_view.ex
- mix.exs
- mix.lock
- priv/repo/migrations/20190307214310_add_email_verification_fields_to_users.exs
- test/idea_portal/accounts_test.exs
- test/web/controllers/registration_verify_controller_test.exs
Closes #6 
Uses a unique token only for use in verification.
> Send an email to verify the user's email address

- lib/idea_portal/accounts.ex
- lib/idea_portal/accounts/user.ex
- lib/web/controllers/account_controller.ex
- lib/web/router.ex
- lib/web/templates/account/edit.html.eex
- lib/web/templates/layout/_header.html.eex
- lib/web/views/account_view.ex
- test/idea_portal/accounts_test.exs
> Added account editing. Fixed account image path

- lib/idea_portal/accounts/user.ex
- lib/idea_portal/challenges.ex
- lib/idea_portal/challenges/challenge.ex
- lib/web/controllers/challenge_controller.ex
- lib/web/plugs/verify_user.ex
- lib/web/router.ex
- lib/web/templates/challenge/index.html.eex
- lib/web/templates/challenge/new.html.eex
- lib/web/templates/layout/app.html.eex
- lib/web/views/challenge_view.ex
- lib/web/views/error_helpers.ex
- priv/repo/migrations/20190308185308_create_challenges.exs
- test/idea_portal/challenges/challenge_test.exs
- test/idea_portal/challenges_test.exs
- test/web/controllers/challenge_controller_test.exs
- test/web/plugs/verify_user_test.exs
Still requires: 
General TODO:
> Submit challenges as a user

- lib/idea_portal/accounts.ex
- lib/idea_portal/accounts/user.ex
- lib/idea_portal/emails.ex
- lib/web/controllers/registration_reset_controller.ex
- lib/web/plugs/verify_no_user.ex
- lib/web/router.ex
- lib/web/templates/account/edit.html.eex
- lib/web/templates/email/password-reset.html.eex
- lib/web/templates/layout/app.html.eex
- lib/web/templates/layout/session.html.eex
- lib/web/templates/registration_reset/edit.html.eex
- lib/web/templates/registration_reset/new.html.eex
- lib/web/templates/session/new.html.eex
- lib/web/views/email_view.ex
- lib/web/views/registration_reset_view.ex
- mix.lock
- priv/repo/migrations/20190313183651_add_password_reset_fields_to_users.exs
- test/web/controllers/registration_reset_controller_test.exs
- test/web/plugs/verify_admin_test.exs
- test/web/plugs/verify_no_user_test.exs
- Send a reset email with a link to reset their password
- Verify any of the signed out controllers are dealt with while signed
out
> Handle password resets

- lib/web/templates/challenge/index.html.eex
> Hide pagination if only 1 page exists

- assets/css/footer.css
- assets/css/style.css
- lib/web/controllers/challenge_controller.ex
- lib/web/controllers/page_controller.ex
- lib/web/controllers/registration_controller.ex
- lib/web/router.ex
- lib/web/templates/challenge/index.html.eex
> Small UX tweaks

- assets/css/style.css
> Changed area filter styling to use checkboxes

- lib/idea_portal/supporting_documents.ex
- mix.lock
> Update stein and allow all file extensions to be uploaded

- assets/css/style.css
> Few tweaks to fix mobile styling on challenges

- lib/idea_portal/accounts.ex
- lib/web/controllers/challenge_controller.ex
- test/support/test_helpers.ex
- test/web/controllers/challenge_controller_test.exs
> Check for the user's email being verified before submitting a challenge

- assets/js/admin.js
- lib/idea_portal/challenges.ex
- lib/idea_portal/challenges/challenge.ex
- lib/idea_portal/supporting_documents.ex
- lib/web/controllers/admin/challenge_controller.ex
- lib/web/controllers/admin/document_controller.ex
- lib/web/controllers/admin/fallback_controller.ex
- lib/web/controllers/challenge_controller.ex
- lib/web/controllers/fallback_controller.ex
- lib/web/endpoint.ex
- lib/web/router.ex
- lib/web/templates/admin/challenge/edit.html.eex
- lib/web/templates/admin/challenge/index.html.eex
- lib/web/templates/admin/challenge/show.html.eex
- lib/web/templates/challenge/show.html.eex
- lib/web/templates/layout/admin.html.eex
- lib/web/views/admin/challenge_view.ex
- lib/web/views/admin/form_view.ex
- lib/web/views/challenge_view.ex
- lib/web/views/layout_view.ex
- lib/web/views/shared_view.ex
- priv/repo/migrations/20190315162658_add_status_to_challenges.exs
- test/idea_portal/challenges_test.exs
- test/idea_portal/supporting_documents_test.exs
- test/web/controllers/admin/document_controller_test.exs
- test/web/controllers/challenge_controller_test.exs
> Admin view/edit challenges

- config/config.exs
- lib/web/templates/challenge/show.html.eex
- lib/web/views/challenge_view.ex
> Add disqus comments to the challenge page

- lib/idea_portal/challenges/challenge.ex
- lib/web/templates/admin/challenge/edit.html.eex
- lib/web/templates/admin/challenge/show.html.eex
- priv/repo/migrations/20190520201827_add_new_fields_to_challenges.exs
> Add new fields to only the admin side of challenges

- lib/web/templates/admin/challenge/index.html.eex
> Added edit button to challenges index on admin

- assets/css/style.css
- lib/web/templates/challenge/new.html.eex
> Made submit challenges form more compact

- lib/idea_portal/challenges.ex
- lib/idea_portal/challenges/challenge.ex
- lib/web/controllers/challenge_controller.ex
- lib/web/templates/admin/challenge/edit.html.eex
- lib/web/templates/admin/challenge/index.html.eex
- lib/web/templates/admin/challenge/show.html.eex
- priv/repo/migrations/20190521140305_add_captured_on_to_challenges.exs
- priv/repo/migrations/20190521153351_rename_published_status_on_challenges.exs
- test/idea_portal/challenges/challenge_test.exs
- test/idea_portal/challenges_test.exs
> Status field updates for a challenge

- lib/web/controllers/challenge_controller.ex
> Updated flash message when submitting a challenge

- assets/css/style.css
- lib/web/templates/challenge/new.html.eex
> Added fields to challenges form and example text

- lib/idea_portal/challenges.ex
- lib/idea_portal/challenges/challenge.ex
- lib/idea_portal/timeline.ex
- lib/idea_portal/timeline/event.ex
- lib/web/controllers/admin/challenge_controller.ex
- lib/web/controllers/admin/event_controller.ex
- lib/web/router.ex
- lib/web/templates/admin/challenge/show.html.eex
- lib/web/templates/admin/event/_form.html.eex
- lib/web/templates/admin/event/edit.html.eex
- lib/web/templates/admin/event/new.html.eex
- lib/web/views/admin/event_view.ex
- priv/repo/migrations/20190521165143_create_timeline_events.exs
- test/idea_portal/challenges_test.exs
- test/idea_portal/timeline_test.exs
- test/support/test_helpers.ex
- test/web/controllers/admin/event_controller_test.exs
> Timeline for challenges

- lib/idea_portal/challenges.ex
- lib/idea_portal/timeline.ex
- mix.exs
- mix.lock
Since the portal will run in Baltimore, we can shift to the known
timezone
> Shift time to the New_York timezone to get today

- lib/idea_portal/accounts.ex
- lib/idea_portal/accounts/user.ex
- lib/idea_portal/emails.ex
- lib/web/controllers/user_invite_accept_controller.ex
- lib/web/controllers/user_invite_controller.ex
- lib/web/router.ex
- lib/web/templates/email/invitation-email.html.eex
- lib/web/templates/layout/app.html.eex
- lib/web/templates/user_invite/new.html.eex
- lib/web/templates/user_invite_accept/new.html.eex
- lib/web/views/account_view.ex
- lib/web/views/email_view.ex
- lib/web/views/user_invite_accept_view.ex
- lib/web/views/user_invite_view.ex
- priv/repo/migrations/20190522182115_add_status_to_users.exs
- test/idea_portal/accounts_test.exs
- test/support/test_helpers.ex
- test/web/controllers/user_invite_accept_controller_test.exs
- test/web/controllers/user_invite_controller_test.exs
> Allow for users to be invited and finish registration

- assets/css/style.css
- lib/idea_portal/accounts.ex
- lib/web/controllers/account_controller.ex
- lib/web/router.ex
- lib/web/templates/account/index.html.eex
- lib/web/templates/account/show.html.eex
- lib/web/templates/layout/app.html.eex
- lib/web/views/account_view.ex
- lib/web/views/layout_view.ex
- test/web/controllers/account_controller_test.exs
> View all participants

- lib/idea_portal/accounts/user.ex
- lib/idea_portal/teams.ex
- lib/idea_portal/teams/member.ex
- lib/idea_portal/teams/team.ex
- lib/web/controllers/admin/team_controller.ex
- lib/web/controllers/team_controller.ex
- lib/web/router.ex
- lib/web/templates/account/show.html.eex
- lib/web/templates/admin/challenge/edit.html.eex
- lib/web/templates/admin/team/edit.html.eex
- lib/web/templates/admin/team/index.html.eex
- lib/web/templates/admin/team/show.html.eex
- lib/web/templates/layout/admin.html.eex
- lib/web/templates/layout/app.html.eex
- lib/web/templates/team/_invite_member.html.eex
- lib/web/templates/team/index.html.eex
- lib/web/templates/team/new.html.eex
- lib/web/templates/team/show.html.eex
- lib/web/views/admin/team_view.ex
- lib/web/views/team_view.ex
- priv/repo/migrations/20190522203136_create_teams.exs
- priv/repo/migrations/20190605192812_add_deleted_at_to_teams.exs
- test/idea_portal/teams_test.exs
- test/support/test_helpers.ex
- test/web/controllers/admin/team_controller_test.exs
- test/web/controllers/team_controller_test.exs
Adds you to the team after creation. Styles are very bare at the moment, but this is the framework for teams. @cpreisinger do we want to just style in this PR before merging?
> Create and view your team

- lib/idea_portal/challenges/challenge.ex
- lib/web/templates/admin/challenge/edit.html.eex
- lib/web/templates/admin/challenge/show.html.eex
- priv/repo/migrations/20190605203035_add_champion_fields_to_challenges.exs
> Add champion name and email to challenges

- assets/js/app.js
- assets/js/teams.js
- lib/idea_portal/accounts.ex
- lib/idea_portal/emails.ex
- lib/idea_portal/teams.ex
- lib/idea_portal/teams/member.ex
- lib/web/controllers/session_controller.ex
- lib/web/controllers/team_controller.ex
- lib/web/controllers/team_invitation_controller.ex
- lib/web/plugs/verify_user.ex
- lib/web/router.ex
- lib/web/templates/email/team-invitation.html.eex
- lib/web/templates/layout/_head.html.eex
- lib/web/templates/team/_invite_member.html.eex
- lib/web/templates/team/show.html.eex
- lib/web/views/account_view.ex
- lib/web/views/team_invitation_view.ex
- lib/web/views/team_view.ex
- priv/repo/migrations/20190607163746_add_status_to_team_members.exs
- test/idea_portal/teams_test.exs
- test/support/test_helpers.ex
- test/web/controllers/team_invitation_controller_test.exs
- test/web/plugs/verify_user_test.exs
> Invite team member

- assets/css/style.css
- lib/web/templates/challenge/show.html.eex
- lib/web/views/challenge_view.ex
> Add colors to past and today on timeline bullets

- lib/idea_portal/challenges.ex
> Only send challenge emails from public

- lib/idea_portal/challenges.ex
- lib/web/controllers/admin/challenge_controller.ex
- lib/web/templates/admin/challenge/index.html.eex
- test/idea_portal/challenges_test.exs
> Show challenge counts on admin challenge index
